//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eterea_Parfums_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class caja
    {
        public int id { get; set; }
        public int numCaja { get; set; }
        public bool disponible { get; set; }
        public int sucursal_id { get; set; }
    
        public virtual sucursal sucursal { get; set; }
    }
}
