//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eterea_Parfums_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carrito
    {
        public int id { get; set; }
        public int perfume_id { get; set; }
        public int cliente_id { get; set; }
        public int cantidad { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual perfume perfume { get; set; }
    }
}
