//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eterea_Parfums_Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.carrito = new HashSet<carrito>();
            this.factura = new HashSet<factura>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "El nombre de usuario es obligatorio")]
        public string usuario { get; set; }
        [Required(ErrorMessage = "La contraseña es obligatoria")]
        public string clave { get; set; }
        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "El apellido es obligatorio")]
        public string apellido { get; set; }
        [Required(ErrorMessage = "El DNI es obligatorio")]
        public long dni { get; set; }
        public string condicion_frente_al_iva { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        [Required(ErrorMessage = "El celuar es obligatorio")]
        public string celular { get; set; }
        [Required(ErrorMessage = "El E_mail es obligatorio")]
        [EmailAddress(ErrorMessage = "Debe ingresar un correo electrónico válido")]
        public string e_mail { get; set; }
        [Required(ErrorMessage = "El pais es obligatorio")]
        public int pais_id { get; set; }
        [Required(ErrorMessage = "La provincia es obligatoria")]
        public int provincia_id { get; set; }
        [Required(ErrorMessage = "La localidad es obligatoria")]
        public int localidad_id { get; set; }
        public Nullable<int> codigo_postal { get; set; }
        [Required(ErrorMessage = "La calle es obligatoria")]
        public int calle_id { get; set; }
        [Required(ErrorMessage = "La numeración de calle es obligatoria")]
        public int numeracion_calle { get; set; }
        public string piso { get; set; }
        public string departamento { get; set; }
        public string comentarios_domicilio { get; set; }
        public bool activo { get; set; }
        public string rol { get; set; }
    
        public virtual calle calle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrito> carrito { get; set; }
        public virtual localidad localidad { get; set; }
        public virtual pais pais { get; set; }
        public virtual provincia provincia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
    }
}
