//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eterea_Parfums_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_factura
    {
        public int factura_id { get; set; }
        public int perfume_id { get; set; }
        public int cantidad { get; set; }
        public double precio_unitario { get; set; }
        public int promocion_id { get; set; }
        public Nullable<int> promocion2_id { get; set; }
    
        public virtual promocion promocion { get; set; }
        public virtual perfume perfume { get; set; }
        public virtual promocion promocion1 { get; set; }
        public virtual factura factura { get; set; }
    }
}
