//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eterea_Parfums_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.factura = new HashSet<factura>();
        }
    
        public int id { get; set; }
        public string usuario { get; set; }
        public string clave { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int dni { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string celular { get; set; }
        public string e_mail { get; set; }
        public int pais_id { get; set; }
        public int provincia_id { get; set; }
        public int localidad_id { get; set; }
        public Nullable<int> codigo_postal { get; set; }
        public int calle_id { get; set; }
        public int numeracion_calle { get; set; }
        public string piso { get; set; }
        public string departamento { get; set; }
        public string comentarios_domicilio { get; set; }
        public int sucursal_id { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public double sueldo { get; set; }
        public bool activo { get; set; }
        public string rol { get; set; }
    
        public virtual calle calle { get; set; }
        public virtual localidad localidad { get; set; }
        public virtual pais pais { get; set; }
        public virtual provincia provincia { get; set; }
        public virtual sucursal sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
    }
}
