//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eterea_Parfums_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public factura()
        {
            this.detalle_factura = new HashSet<detalle_factura>();
            this.orden = new HashSet<orden>();
        }
    
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int sucursal_id { get; set; }
        public int empleado_id { get; set; }
        public int cliente_id { get; set; }
        public string forma_de_pago { get; set; }
        public double precio_total { get; set; }
        public double recargo_tarjeta { get; set; }
        public double descuento { get; set; }
        public int numero_de_caja { get; set; }
        public string tipo_de_consumidor { get; set; }
        public string origen { get; set; }
        public string factura_pdf { get; set; }
        public string num_factura { get; set; }
        public string tipo_de_factura { get; set; }
    
        public virtual cliente cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura> detalle_factura { get; set; }
        public virtual empleado empleado { get; set; }
        public virtual sucursal sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<orden> orden { get; set; }
    }
}
