//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eterea_Parfums_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class etereaEntities1 : DbContext
    {
        public etereaEntities1()
            : base("name=etereaEntities1")
        {
        }

        public etereaEntities1(string nameOrConnectionString)
            : base(nameOrConnectionString)
        {
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<caja> caja { get; set; }
        public virtual DbSet<calle> calle { get; set; }
        public virtual DbSet<carrito> carrito { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<detalle_factura> detalle_factura { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<genero> genero { get; set; }
        public virtual DbSet<historialCaja> historialCaja { get; set; }
        public virtual DbSet<localidad> localidad { get; set; }
        public virtual DbSet<marca> marca { get; set; }
        public virtual DbSet<nota> nota { get; set; }
        public virtual DbSet<nota_con_tipo_de_nota> nota_con_tipo_de_nota { get; set; }
        public virtual DbSet<orden> orden { get; set; }
        public virtual DbSet<pais> pais { get; set; }
        public virtual DbSet<perfume> perfume { get; set; }
        public virtual DbSet<promocion> promocion { get; set; }
        public virtual DbSet<provincia> provincia { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<sucursal> sucursal { get; set; }
        public virtual DbSet<tipo_de_aroma> tipo_de_aroma { get; set; }
        public virtual DbSet<tipo_de_nota> tipo_de_nota { get; set; }
        public virtual DbSet<tipo_de_perfume> tipo_de_perfume { get; set; }
    }
}
