//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eterea_Parfums_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden
    {
        public int numero_de_orden { get; set; }
        public int factura_id { get; set; }
        public string nombre_cliente { get; set; }
        public string apellido_cliente { get; set; }
        public long dni { get; set; }
        public string e_mail_cliente { get; set; }
        public string domicilio_de_envio { get; set; }
        public bool estado { get; set; }
        public Nullable<long> codigo_despacho { get; set; }
        public System.DateTime fecha_creacion { get; set; }
    
        public virtual factura factura { get; set; }
    }
}
