//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eterea_Parfums_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public perfume()
        {
            this.carrito = new HashSet<carrito>();
            this.detalle_factura = new HashSet<detalle_factura>();
            this.stock = new HashSet<stock>();
            this.tipo_de_aroma = new HashSet<tipo_de_aroma>();
            this.nota_con_tipo_de_nota = new HashSet<nota_con_tipo_de_nota>();
            this.promocion = new HashSet<promocion>();
        }
    
        public int id { get; set; }
        public string codigo { get; set; }
        public int marca_id { get; set; }
        public string nombre { get; set; }
        public int tipo_de_perfume_id { get; set; }
        public int genero_id { get; set; }
        public int presentacion_ml { get; set; }
        public int pais_id { get; set; }
        public bool spray { get; set; }
        public bool recargable { get; set; }
        public string descripcion { get; set; }
        public int anio_de_lanzamiento { get; set; }
        public double precio_en_pesos { get; set; }
        public bool activo { get; set; }
        public string imagen1 { get; set; }
        public string imagen2 { get; set; }
        public Nullable<System.DateTime> fecha_baja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carrito> carrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_factura> detalle_factura { get; set; }
        public virtual genero genero { get; set; }
        public virtual marca marca { get; set; }
        public virtual pais pais { get; set; }
        public virtual tipo_de_perfume tipo_de_perfume { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stock> stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tipo_de_aroma> tipo_de_aroma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<nota_con_tipo_de_nota> nota_con_tipo_de_nota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promocion> promocion { get; set; }
    }
}
